# Generated by Django 6.0.5 on 2026-05-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saby_id', models.PositiveIntegerField(blank=True, help_text='ID товара из Saby. Без него товар нельзя отправить в заказ.', null=True, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(blank=True, max_length=60)),
                ('is_new', models.BooleanField(default=False)),
                ('is_hit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saby_id', models.PositiveIntegerField(blank=True, help_text='ID варианта из Saby, например маленькая/средняя/большая пицца.', null=True, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
