# Generated by Django 6.0.5 on 2026-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSabyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Новый товар из Saby',
                'verbose_name_plural': 'Новые товары из Saby',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Товар требует оформления перед публикацией.'),
        ),
        migrations.AddField(
            model_name='product',
            name='saby_name',
            field=models.CharField(blank=True, help_text='Оригинальное название товара из Saby.', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', 'Создан вручную'), ('saby', 'Saby')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='saby_name',
            field=models.CharField(blank=True, help_text='Оригинальное название варианта из Saby.', max_length=180),
        ),
    ]
