# Generated by Django 6.0.6 on 2026-06-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_newsabyproduct_product_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='saby_category_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
