# Generated by Django 6.0.6 on 2026-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_saby_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_app',
            field=models.BooleanField(default=False, verbose_name='Показывать в приложении'),
        ),
    ]
