# Generated by Django 6.0.6 on 2026-06-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_show_in_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_app',
            field=models.BooleanField(default=False, verbose_name='Показывать в приложении'),
        ),
    ]
