# Generated by Django 6.0.6 on 2026-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_show_in_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_category',
            field=models.BooleanField(default=False, verbose_name='Категория назначена вручную'),
        ),
    ]
