"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'unsafe-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'catalog',
    'orders',
    'customers',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Пока используем SQLite для разработки.
# Для продакшна позже перейдём на PostgreSQL.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'delycafe_db'),
        'USER': os.getenv('DB_USER', 'delycafe_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Media files: картинки товаров, загружаемые через админку

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# CORS
# Для разработки разрешаем запросы от Flutter/web.
# В продакшне ограничим конкретным доменом.

CORS_ALLOW_ALL_ORIGINS = True


# Django default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ALFA_PAYMENT_ENABLED = os.getenv(
    'ALFA_PAYMENT_ENABLED',
    'False',
).lower() == 'true'

ALFA_API_BASE_URL = os.getenv(
    'ALFA_API_BASE_URL',
    'https://payment.alfabank.ru/payment/rest',
)

ALFA_API_LOGIN = os.getenv('ALFA_API_LOGIN', '')

ALFA_API_PASSWORD = os.getenv('ALFA_API_PASSWORD', '')

ALFA_RETURN_URL = os.getenv(
    'ALFA_RETURN_URL',
    'http://127.0.0.1:8000/api/payments/success/',
)

ALFA_FAIL_URL = os.getenv(
    'ALFA_FAIL_URL',
    'http://127.0.0.1:8000/api/payments/fail/',
)

ALFA_CALLBACK_URL = os.getenv(
    'ALFA_CALLBACK_URL',
    'https://api.delycafe.ru/api/payments/alfa/callback/',
)

ALFA_REGISTER_URL = os.getenv(
    'ALFA_REGISTER_URL',
    'https://payment.alfabank.ru/payment/rest/register.do',
)

ALFA_STATUS_URL = os.getenv(
    'ALFA_STATUS_URL',
    'https://payment.alfabank.ru/payment/rest/getOrderStatusExtended.do',
)


SABY_APP_CLIENT_ID = os.getenv('SABY_APP_CLIENT_ID', '')
SABY_APP_SECRET = os.getenv('SABY_APP_SECRET', '')
SABY_SECRET_KEY = os.getenv('SABY_SECRET_KEY', '')
SABY_POINT_ID = int(
    os.getenv('SABY_POINT_ID', '187')
)

SABY_PRICE_LIST_ID = int(
    os.getenv('SABY_PRICE_LIST_ID', '4')
)
