# Generated by Django 6.0.5 on 2026-05-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('delivery_type', models.CharField(choices=[('ozersk', 'Озёрск'), ('promploshadka', 'Промплощадка'), ('tatysh', 'Татыш'), ('pickup', 'Самовывоз')], default='ozersk', max_length=30)),
                ('address', models.TextField(blank=True)),
                ('delivery_time_type', models.CharField(choices=[('asap', 'Как можно скорее'), ('by_time', 'Ко времени')], default='asap', max_length=30)),
                ('delivery_time', models.CharField(blank=True, max_length=20)),
                ('payment_type', models.CharField(choices=[('card', 'Картой'), ('sbp', 'СБП')], default='card', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('products_total', models.PositiveIntegerField(default=0)),
                ('delivery_price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('cooking', 'Готовится'), ('delivery', 'В доставке'), ('done', 'Завершён'), ('canceled', 'Отменён')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=180)),
                ('variant_title', models.CharField(blank=True, max_length=80)),
                ('product_api_id', models.CharField(blank=True, max_length=80)),
                ('saby_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
