# Generated by Django 6.0.5 on 2026-06-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Начислено бонусов'),
        ),
        migrations.AddField(
            model_name='order',
            name='bonus_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано бонусов'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_order_discount_applied',
            field=models.BooleanField(default=False, verbose_name='Применена скидка первого заказа'),
        ),
    ]
