# Generated by Django 6.0.5 on 2026-06-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bonus_earned_order_bonus_spent_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма к оплате'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_external_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID платежа у провайдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=60, verbose_name='Платёжный провайдер'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат')], default='unpaid', max_length=30, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_type',
            field=models.CharField(choices=[('asap', 'Как можно скорее'), ('by_time', 'Ко времени')], default='asap', max_length=30, verbose_name='Тип времени доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('ozersk', 'Озёрск'), ('promploshadka', 'Промплощадка'), ('tatysh', 'Татыш'), ('pickup', 'Самовывоз')], default='ozersk', max_length=30, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Картой'), ('sbp', 'СБП')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('cooking', 'Готовится'), ('delivery', 'В доставке'), ('done', 'Завершён'), ('canceled', 'Отменён')], default='new', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_api_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID товара в API'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(max_length=180, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='saby_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Saby ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Вариант'),
        ),
    ]
