# Generated by Django 6.0.6 on 2026-06-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_compensated',
            field=models.BooleanField(default=False, verbose_name='Бонусы компенсированы'),
        ),
    ]
