# Generated by Django 6.0.6 on 2026-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_bonus_compensated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saby_external_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='External ID Saby'),
        ),
        migrations.AddField(
            model_name='order',
            name='saby_order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер заказа Saby'),
        ),
        migrations.AddField(
            model_name='order',
            name='saby_sale_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sale ID Saby'),
        ),
    ]
