from django.urls import path

from .views import (
    CustomerAccountDeleteAPIView,
    CustomerAddressDetailAPIView,
    CustomerAddressesAPIView,
    CustomerAuthMatchAPIView,
    CustomerBonusesAPIView,
    CustomerMobileIdWebhookAPIView,
    CustomerOtpSendAPIView,
    CustomerOtpStatusAPIView,
    CustomerOtpVerifyAPIView,
    CustomerProfileAPIView,
    CustomerSabyLookupAPIView,
    SetDefaultAddressAPIView,
)


urlpatterns = [
    path(
        'auth/otp/send/',
        CustomerOtpSendAPIView.as_view(),
        name='customer-otp-send',
    ),
    path(
        'auth/otp/verify/',
        CustomerOtpVerifyAPIView.as_view(),
        name='customer-otp-verify',
    ),
    path(
        'auth/otp/status/',
        CustomerOtpStatusAPIView.as_view(),
        name='customer-otp-status',
    ),
    path(
        'auth/mobile-id/webhook/',
        CustomerMobileIdWebhookAPIView.as_view(),
        name='customer-mobile-id-webhook',
    ),
    path(
        'auth/match/',
        CustomerAuthMatchAPIView.as_view(),
        name='customer-auth-match',
    ),
    path(
        'saby/lookup/',
        CustomerSabyLookupAPIView.as_view(),
        name='customer-saby-lookup',
    ),
    path(
        'profile/',
        CustomerProfileAPIView.as_view(),
        name='customer-profile',
    ),
    path(
        'bonuses/',
        CustomerBonusesAPIView.as_view(),
        name='customer-bonuses',
    ),
    path(
        'account/delete/',
        CustomerAccountDeleteAPIView.as_view(),
        name='customer-account-delete',
    ),
    path(
        'addresses/',
        CustomerAddressesAPIView.as_view(),
        name='customer-addresses',
    ),
    path(
        'addresses/<int:address_id>/',
        CustomerAddressDetailAPIView.as_view(),
        name='customer-address-detail',
    ),
    path(
        'addresses/<int:address_id>/set-default/',
        SetDefaultAddressAPIView.as_view(),
        name='customer-address-set-default',
    ),
]
