# Generated by Django 6.0.5 on 2026-06-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('bonus_balance', models.PositiveIntegerField(default=0, verbose_name='Баланс бонусов')),
                ('first_order_discount_available', models.BooleanField(default=True, help_text='Доступна скидка 20% на первый заказ в приложении.', verbose_name='Скидка 20% доступна')),
                ('first_order_discount_used', models.BooleanField(default=False, verbose_name='Скидка 20% использована')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Начисление'), ('spend', 'Списание'), ('refund', 'Возврат'), ('manual', 'Ручная корректировка')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.IntegerField(help_text='Положительное число — начисление, отрицательное — списание.', verbose_name='Количество бонусов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бонусная операция',
                'verbose_name_plural': 'Бонусные операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
