# Generated by Django 6.0.5 on 2026-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
    ]
