# Generated by Django 6.0.6 on 2026-06-14 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Количество бонусов'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Начисление'), ('spend', 'Списание'), ('refund', 'Возврат'), ('manual', 'Ручная операция')], max_length=30, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bonus_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусный баланс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_address',
            field=models.TextField(blank=True, verbose_name='Адрес по умолчанию'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_order_discount_available',
            field=models.BooleanField(default=True, verbose_name='Скидка первого заказа доступна'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_order_discount_used',
            field=models.BooleanField(default=False, verbose_name='Скидка первого заказа использована'),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Адрес', max_length=80, verbose_name='Название адреса')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('entrance', models.CharField(blank=True, max_length=30, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=30, verbose_name='Квартира / офис')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к адресу')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
